#!/bin/bash 

#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=8
#PBS -l vmem=60gb
#PBS -M julie.morscio@ugent.be
#PBS -m abe
#PBS -N samtools_view

module load SAMtools/1.15-GCC-11.2.0

#specify wd
$PBS_O_WORKDIR=/data/gent/vo/000/gvo00056/vsc42347/InternshipLeuven/H1_fastq/6_bismark/dedup/filtered

#in for loop, specify $s which refers to the bam file basename
for f in /data/gent/vo/000/gvo00056/vsc42347/InternshipLeuven/H1_fastq/6_bismark/dedup/*.bam
do 
    s=$(basename $f .bam)
    samtools view -bS -@ 6 -F 4 -F 256 -q 10 $f > $PBS_O_WORKDIR/"$s"_filtered.bam
done

