#!/bin/bash -l

#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=8
#PBS -l vmem=60gb
#PBS -M julie.morscio@ugent.be
#PBS -m abe
#PBS -N dedup_bismark

module load Bismark/0.20.1-intel-2018b

$PBS_O_WORKDIR = /data/gent/vo/000/gvo00056/vsc42347/InternshipLeuven/H1_fastq/6_bismark/dedup
cd $PBS_O_WORKDIR

deduplicate_bismark --bam /data/gent/vo/000/gvo00056/vsc42347/InternshipLeuven/H1_fastq/6_bismark/SRR10470168_R*_pair_bismark_bt2.bam
