#!/bin/bash 

#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=8
#PBS -l vmem=60gb
#PBS -M julie.morscio@ugent.be
#PBS -m abe
#PBS -N samtools_merge

module load SAMtools/1.14-GCC-11.2.0

#specify wd
PBS_O_WORKDIR=/data/gent/vo/000/gvo00056/vsc42347/InternshipLeuven/H1_fastq/6_bismark/dedup/filtered/sorted/merge
cd $PBS_O_WORKDIR

for f in ../*_R1_*.bam 
do
    name=$(basename ${f} _R1_pair_bismark_bt2.deduplicated_filtered_sorted.bam)
    samtools merge $PBS_O_WORKDIR/${name}.merged.bam ../${name}_R1_pair_bismark_bt2.deduplicated_filtered_sorted.bam ../${name}_R2_pair_bismark_bt2.deduplicated_filtered_sorted.bam
done





